apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fiovol
spec:
  storageClassName: storageos-rep
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 300Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: ubuntu
spec:
  volumes:
    - name: fiovol
      persistentVolumeClaim:
        claimName: fiovol
    - name: proc1
      hostPath:
        path: /proc   
  containers:
  - name: ubuntu
    securityContext:
      privileged: true
      capabilities:
        add:
        - SYS_ADMIN
    image: ubuntu:latest
    # Just spin & wait forever
    command: [ "/bin/bash", "-c", "--" ]
    args: [ "while true; do sleep 30; done;" ]
    volumeMounts:
      - name: fiovol
        mountPath: /fiovol
      - name: proc1
        mountPath: /proc
        mountPropagation: Bidirectional  
#  nodeSelector:
#    kubernetes.io/hostname: ondat-worker02
